### ISSUE TITLE
Viewing an email gives undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by Frexuz** [markets/maily#19]
Test repo
https://github.com/Frexuz/maily-test

Go to
http://localhost:3000/maily/application_mailer/hello

Error
```
    def correct_number_of_arguments?
      required_arguments.size == arguments.size
    end
```

**Comment by Frexuz** [comment]
My fault. Caused by an empty hooks declarations

```
Maily.hooks_for('ApplicationMailer') do |mailer|
end
```

However, now I have:

```
employee_id = 1

Maily.hooks_for('ApplicationMailer') do |mailer|
  mailer.register_hook(:introduction, employee_id)
end
```

**ActionController::UnfilteredParameters in Maily::Emails#show**

Showing /var/www/example.com/vendor/gems/maily-0.6.0/app/views/maily/emails/show.html.erb where line #21 raised:

`unable to convert unpermitted parameters to hash`

**Comment by markets** [comment]
Hi @Frexuz, I'll take a look and I'll come back here with more info.

**Comment by markets** [comment]
Hi again @Frexuz I just pushed a branch (#20) to fix all this stuff. It's not fully ready to cut a new version but it works for me using your sample app:

![screen shot 2017-07-28 at 19 03 31](https://user-images.githubusercontent.com/576701/28728145-cc21ba24-73c7-11e7-8d97-983d38e52376.png)

**Comment by Frexuz** [comment]
Works :)

**Comment by markets** [comment]
@Frexuz v0.6.2 pushed 🚀  to RubyGems: https://rubygems.org/gems/maily/versions/0.6.2

**Comment by Frexuz** [comment]
Nice :D Thanks for the quick help!
