### ISSUE TITLE
Edit mail fails with slim as a template engine

### ISSUE THREAD

**Issue by pablocrivella** [markets/maily#25]
### Description

Currently when you try to edit an email on an application using `slim` as a template engine you get the following error:

```ruby
Errno::ENOENT in Maily::EmailsController#edit
No such file or directory @ rb_sysopen - /../email.text.erb
```

**Comment by markets** [comment]
@pablocrivella I just released a new version (v0.7.2) fixing this, let me know how it works!

Rubygems: https://rubygems.org/gems/maily/versions/0.7.2
Changelog: https://github.com/markets/maily/blob/master/CHANGELOG.md#072

**Comment by pablocrivella** [comment]
Now i get the following error:

```
TypeError in Maily::EmailsController#edit
no implicit conversion of nil into String

def template(part = nil)
   File.read(path(part))
end

maily (0.7.2) lib/maily/email.rb:94:in `read'
maily (0.7.2) lib/maily/email.rb:94:in `template'
```

**Comment by markets** [comment]
Ok @pablocrivella could you please share your emails structure and template files paths?

**Comment by pablocrivella** [comment]
```ruby
class ApplicationMailer < ActionMailer::Base
  default from: "from@example.com"
  layout "mailer/mailer"

  def self.inherited(subclass)
    subclass.default template_path: "mailers/#{subclass.name.to_s.underscore}"
  end
end
```

```
app/
  mailers/
     application_mailer.rb
     caregiver_mailer.rb
  views/
     mailers/
        caregiver_mailer/
           mailer.html.slim
```

**Comment by pablocrivella** [comment]
@markets Maybe this is is no longer about `slim` but about having a different file structure for mailer views?

**Comment by markets** [comment]
@pablocrivella totally! since you're using a custom structure, you should tell it to Maily too (via a [hook](https://github.com/markets/maily/#hooks)). Something like:

```ruby
Maily.hooks_for('CaregiverMailer') do |mailer|
  mailer.register_hook(:a_random_email, template_path: 'mailers/caregiver_mailer')
end
```
