### ISSUE TITLE
Configured available locales not being picked up by maily

### ISSUE THREAD

**Issue by pablocrivella** [markets/maily#27]
### Description

With the following configuration options:

```ruby
# config/application.rb
config.i18n.available_locales = %i[en nl]
config.i18n.default_locale = :nl
```

I get this:

<img width="492" alt="maily - caregiver mailer new job offer notification 2018-06-23 11-40-47" src="https://user-images.githubusercontent.com/1854923/41808191-4cbd1cc6-76da-11e8-882d-4f7e79b56af9.png">

Explicitly setting:

```ruby
config.available_locales = I18n.available_locales
```

on `config/initializers/maily.rb` also doesn't fix the issue because at that point `I18n.available_locales` has all the locales.

**Comment by markets** [comment]
Yep, that also happened to me a couple of times, at this point `I18n.available_locales`, got a lot of locales coming from other gems. I think this should be "fixed" by:

```ruby
Maily.setup do |config|
  config.available_locales = Rails.application.config.i18n.available_locales
```

Maybe this would be a better default in general:

```diff
diff --git a/lib/maily.rb b/lib/maily.rb
index f43fbf2..352e460 100644
--- a/lib/maily.rb
+++ b/lib/maily.rb
@@ -13,7 +13,7 @@ module Maily
       self.enabled            = Rails.env.production? ? false : true
       self.allow_edition      = Rails.env.production? ? false : true
       self.allow_delivery     = Rails.env.production? ? false : true
-      self.available_locales  = I18n.available_locales
+      self.available_locales  = Rails.application.config.i18n.available_locales || I18n.available_locales
       self.base_controller    = 'ActionController::Base'
       self.http_authorization = nil
       self.hooks_path         = "lib/maily_hooks.rb"
```

**Comment by markets** [comment]
hi @pablocrivella I finally pushed a change to improve `Maily` defaults: https://github.com/markets/maily/commit/be46fa5fbfc8d5e85dc40ab13449b843969d7193 🎉
