### ISSUE TITLE
Arrays in arguments of mailer.register_hook is not supported

### ISSUE THREAD

**Issue by cenxky** [markets/maily#41]
Hi @markets,

Thanks for your Maily gem, it lets us easier to preview and test Emails. During working with it, I found `mailer.register_hook` doesn't support Array type arguments. 

```ruby
class Notifier < ActionMailer::Base
  def test_mail(to_mails, cc_mails)
     mail to: to_mails,  cc: cc_mails, subject: "Test"
  end
end

to_mails = %w(a@example.com b@example.com)
cc_mails = %w(c@example.com d@example.com)

Maily.hooks_for('Notifier') do |mailer|
  mailer.register_hook(:test_mail, to_mails, cc_mails)
end
```

The codes above will raise an error while running:

```ruby
test_mail email requires at the most 2 arguments, passed 4
```
So I made a PR to fix it, pls have a look!

Merci!

**Comment by markets** [comment]
hi @cenxky and thanks a lot! I'm totally ok to add support for arrays
